package se.ivankrizsan.springdata.dynamodb.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

import java.util.List;

/**
 * Represents a circle shape with a given radius.
 * Cannot extract common properties that need to be annotated with DynamoDB annotations to
 * superclass(es) since the DynamoDB library will fail with errors in such a case.
 *
 * @author Ivan Krizsan
 */
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "Circles")
public class Circle {
    /* Constant(s): */
    public static final int DEFAULT_RADIUS = 10;

    /* Instance variable(s): */
    /** Entity id. */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    protected String id;
    /** Circle colour. */
    @DynamoDBAttribute
    protected String colour;
    /** Circle location x-coordinate. */
    @DynamoDBAttribute
    protected int x;
    /** Circle location y-coordinate. */
    @DynamoDBAttribute
    protected int y;
    /** Circle radius. */
    @DynamoDBAttribute
    protected int radius = DEFAULT_RADIUS;
    /** Auto-generated timestamp at which the circle created or updated. */
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.N)
    @DynamoDBAttribute
    protected DateTime lastUpdateTime;

    /**
     * Sets the position of the circle to the supplied coordinates.
     *
     * @param inX X-coordinate of circle position.
     * @param inY Y-coordinate of circle position.
     */
    public void setPosition(final int inX, final int inY) {
        x = inX;
        y = inY;
    }
}
